### ISSUE TITLE
CK error: [program] no registered CK environment was found

### ISSUE THREAD

**Issue by Iceomj** [ctuning/ck-request-asplos18-resnet-tvm-fpga#1]
During the installation: PYNQ-Z1 FPGA: 
when I kick off "ck run program:vta-pynq-server --sudo"

it shows the below info in the end:

> **Resolving software dependencies ...                                                                                                                         
>                                                                                                                                                               
> *** Dependency 1 = python (Python):                                                                                                                           
>                                                                                                                                                               
>     Resolved. CK environment UID = 8426ebabf423cd15 (detected version 3.4.3+)                                                                                 
>                                                                                                                                                               
> *** Dependency 2 = compiler (Compiler):                                                                                                                       
>                                                                                                                                                               
>     Resolved. CK environment UID = 3b82a7951db9c822 (detected version 5.2.1)                                                                                  
>                                                                                                                                                               
> *** Dependency 3 = lib-pynq-dma (PYNQ DMA library):                                                                                                           
>                                                                                                                                                               
>  ********                                                                                                                                                     
>  WARNING: no registered CK environment was found for "PYNQ DMA library" dependency with tags="lib,pynq-dma" and setup={"host_os_uoa": "linux-32", "target_os_u
> oa": "linux-32", "target_os_bits": "32"}                                                                                                                      
>                                                                                                                                                               
>   Trying to automatically detect required software ...                                                                                                        
>                                                                                                                                                               
>   1) Checking if "PYNQ DMA library" (lib.pynq.dma / 044f569eca5ec2ba) is installed ...                                                                        
>                                                                                                                                                               
>   Searching for PYNQ DMA library (libdma.so) to automatically register in the CK - it may take some time, please wait ...                                     
>                                                                                                                                                               
>     * Searching in /usr ...                                                                                                                                   
>     * Searching in /opt ...                                                                                                                                   
>     * Searching in /root ...                                                                                                                                  
>                                                                                                                                                               
>   Search completed in 7.3 secs. Found 0 target files (may be pruned) ...                                                                                      
>   (warning during intermediate step: software was not automatically found on your system! Please, install it and re-try again!)                               
>     No software auto-detection scripts found for this software in CK :( ...                                                                                   
>                                                                                                                                                               
>        Checked following related CK soft entries:                                                                                                             
>         * lib.pynq.dma                                                                                                                                        
>                                                                                                                                                               
>   Searching and installing CK software packages ...                                                                                                           
>     * tags:        lib,pynq-dma                                                                                                                               
>     * or tags:                                                                                                                                                
>     * no tags:                                                                                                                                                
>                                                                                                                                                               
>     CK packages are not found for this software :( !                                                                                                          
>                                                                                                                                                               
>        Would you like to open wiki pages about installation and other info (if exists) (Y/n): y                                                               
>                                                                                                                                                               
> Opening web page https://github.com/ctuning/ck/wiki/ckb_5e1100048ab875d7_044f569eca5ec2ba ...                                                                 
>                                                                                                                                                               
>        Would you like to manually register software, i.e. if it is in an unusual path (y/N): n                                                                
>                                                                                                                                                               
> CK error: [program] no registered CK environment was found for "PYNQ DMA library" dependency with tags="lib,pynq-dma" and setup={"host_os_uoa": "linux-32", "target_os_uoa": "linux-32", "target_os_bits": "32"}!**

**Comment by gfursin** [comment]
Hi @Iceomj . 

Did you use "pynq_z1_image_2017_02_10.img" (https://github.com/ctuning/ck-request-asplos18-resnet-tvm-fpga#installation-pynq-z1-fpga-connected-via-rpc-from-host) when flashing your board? 

CK needs to find file libdma.so to run server. If it's not in a standard path, you can try to find it yourself and then register in the CK manually as following:
```
$ ck detect soft:lib.pynq.dma --search_dirs={path to libdma.so)
```
Please tell me if it works. Thanks.

CC @tmoreau89 @tqchen @psyhtest

**Comment by Iceomj** [comment]
it works! But another error occured:

> Cloning package from https://github.com/uwsaml/vta.git/ ...                                                                                                   
> Cloning into 'src'...                                                                                                                                         
> Username for 'https://github.com': Iceomj                                                                                                                     
> Password for 'https://Iceomj@github.com':                                                                                                                     
> remote: Repository not found.                                                                                                                                 
> fatal: repository 'https://github.com/uwsaml/vta.git/' not found                                                                                              
> Error: git cloning failed!                                                                                                                                    
> CK error: [program] package installation failed!          

so I check the repository  https://github.com/uwsaml/vta.git but only found 
 https://github.com/uwsaml/vta-distro.git

Then I tried to revise it. So I grep the vta.git 

> root@pynq:~/CK# grep -rn "https://github.com/uwsaml/vta.git"                                                                                                  
> ck-request-asplos18-resnet-tvm-fpga/package/lib-vta-server-master-pynq/.cm/meta.json:22:      "PACKAGE_URL": "https://github.com/uwsaml/vta.git",             
> ck-request-asplos18-resnet-tvm-fpga/package/lib-vta-python-master/.cm/meta.json:22:      "PACKAGE_URL": "https://github.com/uwsaml/vta.git",                  

So I fixed the meta.json "vta.git" to “vta-distro.git”. And I think it make sense, so I go on.

> root@pynq:~/CK# ck run program:vta-pynq-server --sudo
> ......................
> Cloning package from https://github.com/uwsaml/vta-distro.git/ ...                                                                                            
> Cloning into 'src'...                                                                                                                                         
> remote: Counting objects: 16, done.                                                                                                                           
> remote: Compressing objects: 100% (12/12), done.                                                                                                              
> remote: Total 16 (delta 0), reused 13 (delta 0), pack-reused 0                                                                                                
> Unpacking objects: 100% (16/16), done.                                                                                                                        
> Checking connectivity... done.                                                                                                                                
>                                                                                                                                                               
> Cleaning ...                                                                                                                                                  
>                                                                                                                                                               
> Executing extra script ...                                                                                                                                    
> **************************************************************                                                                                                
> Preparing vars for VTA ...                                                                                                                                    
> /root/CK-TOOLS/lib-vta-gcc-5.2.1-linux-32/src                                                                                                                 
> make: *** No targets specified and no makefile found.  Stop.                                                                                                  
> Error: make failed!                                                                                                                                           
> CK error: [program] package installation failed!          

> root@pynq:~/CK-TOOLS/lib-vta-gcc-5.2.1-linux-32/src# ls                                                                                                       
> bitstreams  LICENSE  

so I think there should be a Makefile in the vta-distro.git but no Makefile found. 

Do you have some ideas about this error? Thanks a lot.

**Comment by gfursin** [comment]
Hi @Iceomj - I believe @tmoreau89 and @tqchen are finalizing a release for https://github.com/uwsaml/vta.git right now and will do it soon. That's why it's still closed. But you need to use this one (I realized that we had an access to it as a part of Artifact Evaluation). You can ask them for a "preview" access to this repository too... I wil ping them in Collective Knowledge Slack too ... Thanks!

**Comment by tmoreau89** [comment]
Hi @lceomj - we can give you early alpha access to the VTA repository. Please send us your github username, full name, affiliation, and email address associated to your affiliation to moreau@uw.edu.

**Comment by Iceomj** [comment]
Hi @gfursin @tmoreau89 - Thanks a lot for your help! I've sent the email for to moreau and looking forward to your reply :)
